version: '3'

services:

  nginx:

    container_name: nginx
    build: requirements/nginx/
#depends_on signifie que le container ne demarrera pas tant que l'autre n'est pas construit 
    depends_on:
      - wordpress
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "~/Desktop/inception/website:/var/www/html"
    networks:
      - inception
    restart: always


  mariadb:

    container_name: mariadb
    build:
      context: .
      dockerfile: requirements/mariadb/Dockerfile
#On transfert nos infos secretes via args
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
        DB_ROOT: ${DB_ROOT}
    ports:
      - "3306:3306"
    volumes:
       - "~/Desktop/inception/mariadb:/var/lib/mysql"
    networks:
      - inception
    restart: always


  wordpress:

    container_name: wordpress
    build:
      context: .
      dockerfile: requirements/wordpress/Dockerfile
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS} 
        WP_ADMIN: ${WP_ADMIN}
        WP_ADMIN_PASS: ${WP_ADMIN_PASS}
        WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
        WP_USER: ${WP_USER}
        WP_USER_EMAIL: ${WP_USER_EMAIL}
        WP_USER_PASS: ${WP_USER_PASS}
        DOMAIN_NAME: ${DOMAIN_NAME}
    depends_on:
      - mariadb
    volumes:
      - "~/Desktop/inception/website:/var/www/html"
    ports:
      - "9000:9000"
    networks:
      - inception
    restart: always


  redis:

    container_name: redis
    build: requirements/bonus/redis/
    ports:
      - "6379:6379"
    networks:
      - inception
    restart: always

  vsftpd:
    container_name: vsftpd
    build:
      context: .
      dockerfile: requirements/bonus/vsftpd/Dockerfile
      args:
        FTP_USR: ${FTP_USR}
        FTP_PWD: ${FTP_PWD}
    ports:
      - "21:21"
    volumes:
      - "~/Desktop/inception/website:/var/www/html/"
    networks:
      - inception
    restart: always

#Creation de notre nom de docker-network pour y acceder (il fait le lien entre les containers)
networks:
  inception:
    driver: bridge

  
